-- Treesitter support for tufte colorscheme
local Util = require("tufte.utils")

local M = {}

---@param c ColorScheme
---@param opts tufte.Config
---@return tufte.Highlights
function M.get(c, opts)
  -- stylua: ignore
  return {
    ["@annotation"]                 = "PreProc",
    ["@attribute"]                  = "PreProc",
    ["@boolean"]                    = "Boolean",
    ["@character"]                  = "Character",
    ["@character.printf"]           = "SpecialChar",
    ["@character.special"]          = "SpecialChar",
    ["@comment"]                    = "Comment",
    ["@comment.error"]              = { fg = c.error },
    ["@comment.hint"]               = { fg = c.hint },
    ["@comment.info"]               = { fg = c.info },
    ["@comment.note"]               = { fg = c.hint },
    ["@comment.todo"]               = { fg = c.highlight },
    ["@comment.warning"]            = { fg = c.warning },
    ["@constant"]                   = "Constant",
    ["@constant.builtin"]           = "Special",
    ["@constant.macro"]             = "Define",
    ["@constructor"]                = { fg = c.bright_foreground },
    ["@constructor.tsx"]            = { fg = c.bright_foreground },
    ["@diff.delta"]                 = "DiffChange",
    ["@diff.minus"]                 = "DiffDelete",
    ["@diff.plus"]                  = "DiffAdd",
    ["@function"]                   = "Function",
    ["@function.builtin"]           = "Special",
    ["@function.call"]              = { fg = c.bright_foreground, bold = true, style = opts.styles.functions },
    ["@function.macro"]             = "Macro",
    ["@function.method"]            = "Function",
    ["@function.method.call"]       = "@function.call",
    ["@keyword"]                    = { fg = c.foreground, style = opts.styles.keywords },
    ["@keyword.conditional"]        = "Conditional",
    ["@keyword.coroutine"]          = "@keyword",
    ["@keyword.debug"]              = "Debug",
    ["@keyword.directive"]          = "PreProc",
    ["@keyword.directive.define"]   = "Define",
    ["@keyword.exception"]          = "Exception",
    ["@keyword.function"]           = { fg = c.foreground, style = opts.styles.functions },
    ["@keyword.import"]             = "Include",
    ["@keyword.operator"]           = "@operator",
    ["@keyword.repeat"]             = "Repeat",
    ["@keyword.return"]             = "@keyword",
    ["@keyword.storage"]            = "StorageClass",
    ["@label"]                      = { fg = c.foreground },
    ["@markup"]                     = "@none",
    ["@markup.emphasis"]            = { italic = true },
    ["@markup.environment"]         = "Macro",
    ["@markup.environment.name"]    = "Type",
    ["@markup.heading"]             = "Title",
    ["@markup.italic"]              = { italic = true },
    ["@markup.link"]                = { fg = c.dark_foreground },
    ["@markup.link.label"]          = "SpecialChar",
    ["@markup.link.label.symbol"]   = "Identifier",
    ["@markup.link.url"]            = "Underlined",
    ["@markup.list"]                = { fg = c.dark_foreground },
    ["@markup.list.checked"]        = { fg = c.bright_foreground },
    ["@markup.list.markdown"]       = { fg = c.light_foreground, bold = true },
    ["@markup.list.unchecked"]      = { fg = c.foreground },
    ["@markup.math"]                = "Special",
    ["@markup.raw"]                 = "String",
    ["@markup.raw.markdown_inline"] = { bg = c.darker_background, fg = c.foreground },
    ["@markup.strikethrough"]       = { strikethrough = true },
    ["@markup.strong"]              = { bold = true },
    ["@markup.underline"]           = { underline = true },
    ["@module"]                     = "Include",
    ["@module.builtin"]             = { fg = c.foreground },
    ["@namespace.builtin"]          = "@variable.builtin",
    ["@none"]                       = {},
    ["@number"]                     = "Number",
    ["@number.float"]               = "Float",
    ["@operator"]                   = { fg = c.dark_foreground },
    ["@property"]                   = { fg = c.bright_foreground },
    ["@punctuation.bracket"]        = { fg = c.dark_foreground },
    ["@punctuation.delimiter"]      = { fg = c.dark_foreground },
    ["@punctuation.special"]        = { fg = c.dark_foreground },
    ["@punctuation.special.markdown"] = { fg = c.light_foreground },
    ["@string"]                     = "String",
    ["@string.documentation"]       = { fg = c.foreground },
    ["@string.escape"]              = { fg = c.bright_foreground },
    ["@string.regexp"]              = { fg = c.light_foreground },
    ["@tag"]                        = "Label",
    ["@tag.attribute"]              = "@property",
    ["@tag.delimiter"]              = "Delimiter",
    ["@tag.delimiter.tsx"]          = { fg = Util.blend_bg(c.foreground, 0.7) },
    ["@tag.tsx"]                    = { fg = c.foreground },
    ["@tag.javascript"]             = { fg = c.foreground },
    ["@type"]                       = "Type",
    ["@type.builtin"]               = { fg = Util.blend_bg(c.bright_foreground, 0.8) },
    ["@type.definition"]            = "Typedef",
    ["@type.qualifier"]             = "@keyword",
    ["@variable"]                   = { fg = c.bright_foreground, style = opts.styles.variables },
    ["@variable.builtin"]           = { fg = c.bright_foreground },
    ["@variable.member"]            = { fg = c.bright_foreground },
    ["@variable.parameter"]         = { fg = c.foreground },
    ["@variable.parameter.builtin"] = { fg = Util.blend_fg(c.foreground, 0.8) },
  }
end

return M
