#!/bin/bash
# ===========================================================================
#  make-prototype.sh — Generate palettes.css from Lua palette files.
#
#  Reads every lua/tufte/palettes/*.lua and writes prototype/palettes.css
#  with CSS custom properties that drive the prototype viewer.
#
#  Usage:
#    ./make-prototype.sh
#    # then open prototype/tufte-colors.html in a browser
# ===========================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PALETTE_DIR="$PROJECT_DIR/lua/tufte/palettes"
OUTPUT="$SCRIPT_DIR/palettes.css"

# ---- helpers ---------------------------------------------------------------

# Darken a hex colour by a percentage (100 = unchanged, 90 = 90% luminance).
darken_hex() {
  local hex=$1 pct=$2
  local r=$((16#${hex:1:2} * pct / 100))
  local g=$((16#${hex:3:2} * pct / 100))
  local b=$((16#${hex:5:2} * pct / 100))
  printf "#%02x%02x%02x" "$r" "$g" "$b"
}

# Extract the first "#hexvalue" on a line.
extract_hex() {
  sed -n 's/.*"\(#[0-9a-fA-F]*\)".*/\1/p'
}

# ---- main ------------------------------------------------------------------

mkdir -p "$(dirname "$OUTPUT")"

{
  cat <<'HEADER'
/* ==========================================================================
 *  palettes.css — Auto-generated by make-prototype.sh.
 *
 *  DO NOT EDIT DIRECTLY.  To regenerate:
 *    cd prototype && ./make-prototype.sh
 *
 *  Each palette variant is a class on :root that sets CSS custom properties
 *  consumed by tufte-colors.html.
 * ========================================================================== */

HEADER

  for lua_file in "$PALETTE_DIR"/*.lua; do
    [ -f "$lua_file" ] || continue
    name=$(basename "$lua_file" .lua)

    # Extract values from Lua
    bg=$(extract_hex < <(grep 'bg *=.*"' "$lua_file"))
    tiers=()
    while IFS= read -r line; do
      tiers+=("$line")
    done < <(sed -n '/tiers = {/,/^  *}/p' "$lua_file" | grep '"#' | extract_hex)

    accent=$(extract_hex < <(grep 'accent *=.*"' "$lua_file"))
    highlight=$(extract_hex < <(grep 'highlight *=.*"' "$lua_file"))
    secondary=$(extract_hex < <(grep 'secondary *=.*"' "$lua_file"))

    # First line of the Lua file is a `--` comment → palette subtitle
    desc=$(head -1 "$lua_file" | sed 's/^-- *//')

    # Derive wallpaper: bg darkened by 10 %
    wallpaper=$(darken_hex "$bg" 90)

    # Write the CSS class
    echo "/* ${desc}  */"
    echo ":root.palette-${name} {"

    echo "  --bg: ${bg};"
    for i in "${!tiers[@]}"; do
      echo "  --t$((i + 1)): ${tiers[$i]};"
    done
    echo "  --accent: ${accent};"
    echo "  --highlight: ${highlight};"
    echo "  --secondary: ${secondary};"
    echo "  --wallpaper: ${wallpaper};"

    echo "}"
    echo ""

  done
} >"$OUTPUT"

echo "✔  Generated $OUTPUT"
echo "   Palettes found: $(ls "$PALETTE_DIR"/*.lua 2>/dev/null | wc -l)"
